### ISSUE TITLE
All line breaks will be removed after copying.

### ISSUE THREAD

**Issue by bb33bb** [CopyPlusPlus/CopyPlusPlus-Qt#25]
All line breaks will be removed after copying.

**Comment by bb33bb** [comment]
chrome open the pdf ,and copy contents.
All of contents will be in One Paragraph even thourgh there should be multi Paragraphs

**Comment by wy-luke** [comment]
> chrome open the pdf ,and copy contents. All of contents will be in One Paragraph even thourgh there should be multi Paragraphs

对，目前这个问题还没有好的解决办法，C#版本有一个根据换行处符号判断是否段末的功能，但是非常不准确，不是一个好的解决办法，所以这里就没加上。
现在这个版本还在开发中，后面我再看看有没有更优雅的解决方式。

**Comment by bb33bb** [comment]
> 

谢谢！
