### ISSUE TITLE
Static Linking with QT

### ISSUE THREAD

**Issue by pa-0** [CopyPlusPlus/CopyPlusPlus-Qt#28]
Wondering if you've managed to build a single executable for Windows using GitHub CI?

**Comment by wy-luke** [comment]
I kinda forget whether it's a sigle executable. I tried to rerun it, but it failed....

I looked into my workflow file and I think that there is not step for building a single executable for Windows. It's very likely that I used a software called EnigmaVirtualBox to generate a single exe.
